name: Java CI
on: [push]
jobs:
  Build-Project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Configure JDK
        uses: actions/setup-java@91d3aa4956ec4a53e477c4907347b5e3481be8c9 # v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Run Maven Build
        run: mvn package
      #- name: Publish Snapshots and JavaDocs
      #  env:
      #    CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
      #    CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
      #  run: mvn clean source:jar javadoc:jar deploy --settings=".buildscript/settings.xml" -Dmaven.test.skip=true
