name: Java CI
on: [push]
jobs:
  Build-Project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - name: Configure JDK
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Run Maven Build
        run: mvn package
      #- name: Publish Snapshots and JavaDocs
      #  env:
      #    CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
      #    CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
      #  run: mvn clean source:jar javadoc:jar deploy --settings=".buildscript/settings.xml" -Dmaven.test.skip=true
